### PR TITLE
Revert config

### PR DESCRIPTION
**Pull request by keiyamamo**
Ref #75

### CODE REVIEW

**Comment by johannesring** [comment]
@keiyamamo - Is `pyaml` no longer needed now? Can it be removed?

**Comment by keiyamamo** [comment]
@johannesring  I tested deleting `pyaml` and it is still necessary.

**Comment by keiyamamo** [comment]
@johannesring  
I tried to remove `pyaml` but then I got the following error from `domain.py`.
``` 
 File "/Users/keiyamamoto/Documents/turtleFSI/turtleFSI/modules/domain.py", line 103, in assign_domain_properties
    assert isinstance(solid_properties, list), "solid_properties must be a list of dictionaries"
AssertionError: solid_properties must be a list of dictionaries
```
Even though `solid_properties` was passed correctly as parameter, it is `str` and not `list` or `dictionary`.  I would say keeping `pyaml` is the easiest for now. If this seems fine, I will merge the PR.

**Review by johannesring — APPROVED** [review]
Looks good!

**Pull request merged**
